version: '3.8'
services:
  stats-service:
    build: ./stats-service/server
    image: ewm-stat-service
    container_name: ewm_stat_service_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_HOST=stats-db
      - DB_PORT=5432
      - DB_NAME=ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: ewm_stats_db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  main-service:
    build: ./main-service
    image: ewm-main-service
    container_name: ewm_main_service_container
    ports:
      - "8080:8080"
    depends_on:
      - stats-service
      - main-db
    environment:
      - DB_HOST=main-db
      - DB_PORT=5432
      - DB_NAME=ewm-main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  main-db:
    image: postgres:14-alpine
    container_name: ewm_main_db_container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root