-- создаём таблицу stats (со статистикой):
CREATE TABLE IF NOT EXISTS stats(
    stat_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    app varchar(40) NOT NULL,
    uri varchar(100) NOT NULL,
    ip varchar(40) NOT NULL,
    creation_date timestamp NOT NULL,
    CONSTRAINT pk_stat PRIMARY KEY (stat_id)
);